# Introducción a NumPy

**Referencias:**

- https://www.freecodecamp.org/espanol/news/la-guia-definitiva-del-paquete-numpy-para-computacion-cientifica-en-python/
- https://numpy.org/doc/stable/
- http://www.denebola.org/japp/CC/numpy.html

*Esencialmente* NumPy es una biblioteca donde la estructura más destacada es la de *arreglo* o *array* en inglés. NumPy también permite a los desarrolladores o usuarios de Python realizar en forma rápida una amplia variedad de cálculos numéricos en arreglos considerados "inmensos".

Es de mucho uso en las aplicaciones numéricas y  en ciencia de datos.

## 1. ¿Qué es NumPy?
NumPy es el paquete fundamental para la computación científica en Python. Es una biblioteca de Python que proporciona matrices multidimensionales, varios objetos derivados (como matrices y matrices enmascaradas), y un surtido de rutinas para realizar operaciones rápidas con matrices, incluyendo operaciones matemáticas, lógicas, de manipulación de formas, de ordenación, de selección, de E/S, de transformadas discretas de Fourier, de álgebra lineal básica, de operaciones estadísticas básicas, de simulación aleatoria y mucho más.

**Principales características**

1. POTENTES ARRAYS N-DIMENSIONALES.
Rápidos y versátiles, los conceptos de vectorización, indexación y difusión de NumPy son los estándares de facto de la computación de arrays hoy en día.
2. HERRAMIENTAS DE CÁLCULO NUMÉRICO.
NumPy ofrece funciones matemáticas completas, generadores de números aleatorios, rutinas de álgebra lineal, transformadas de Fourier y mucho más.
3. INTEROPERABLE. NumPy es compatible con una amplia gama de plataformas de hardware y de computación, y funciona bien con bibliotecas distribuidas, de GPU y de matrices dispersas.
4. RENDIMIENTO. El núcleo de NumPy es un código C bien optimizado. Se utiliza la flexibilidad de Python y la velocidad del código compilado.
5. FÁCIL DE USAR. La sintaxis de alto nivel de NumPy lo hace accesible y productivo para programadores de cualquier nivel de experiencia.
6. CÓDIGO ABIERTO. Distribuido bajo una licencia  BSD, NumPy es desarrollado y mantenido públicamente en GitHub por una activa comunidad de programadores.

## 2. Instalación de NumPy

En Colab no es necesario hacer ninguna instalación para utilizar NumPy, solo hay que importarlo y usarlo.

En  el caso de una instalación de Python en una PC, se debe instalar haciendo


```
pip install numpy
```

En  Colab o una vez instalado en  una PC se lo puede utilizar haciendo la siguiente instrucción:


In [ ]:
import numpy as np

La tradición es renombrar `numpy` como `np`, pero se podría haber elegido otro nombre.

## 3. Arreglos de NumPy: introducción
En esta sección aprenderemos algunas características de los arreglos de NumPy.

**¿Qué son los Arreglos de NumPy?**

Los arreglos NumPy son la forma principal de almacenar datos utilizando la biblioteca NumPy. Son similares a las listas normales en Python, pero tienen la ventaja de ser más rápidos y tener más métodos integrados.

Los arreglos de NumPy son creados llamando al método `array()` de la biblioteca de NumPy. Dentro del método, se debería pasar una lista.

A continuación, se muestra un ejemplo de un arreglo de NumPy básico.


In [ ]:
sample_list = [1, 2, 3]
arreglo_np = np.array(sample_list)
print(type(arreglo_np), arreglo_np)

<class 'numpy.ndarray'> [1 2 3]


Otro ejemplo:

In [ ]:
sample_list = [1.0, 2, 3]
print(np.array(sample_list))
np.array(sample_list)

[1. 2. 3.]


array([1., 2., 3.])

Como hemos observado, la última línea de ese bloque de código dará como resultado una salida que se ve así.

```
array([1.,2.,3.])
```

El contenedor `array()` indica que esta ya no es una lista normal de Python. En cambio, es un arreglo de NumPy.

Además,  como uno de los números ingresados es  un `float`, convierte todo a `float`.



**Los dos tipos diferentes de arreglos de NumPy**

Hay dos tipos diferentes de arreglos de NumPy: *vectores* y *matrices.*

Los vectores son arreglos de NumPy uni-dimensionales y se ven así:

```
my_vector = np.array(['este', 'es', 'un', 'vector'])
```

Las matrices son arreglo bi-dimensionales y son creadas pasando una lista de listas dentro del método `np.array()`. Un ejemplo es el siguiente.

```
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
np.array(my_matrix)
```

También se pueden expandir los arreglos de NumPy para trabajar con matrices de tres, cuatro, cinco, seis o más dimensiones.

In [ ]:
my_matrix = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]
print('Tipo de my_matrix:', type(my_matrix))
print('Tipo de un elemento de my_matrix:',type(my_matrix[0]))
matriz = np.array(my_matrix)
print('Tipo de matriz:',type(matriz))
print('Tipo de un elemento de matriz:',type(matriz[0]))

Tipo de my_matrix: <class 'list'>
Tipo de un elemento de my_matrix: <class 'list'>
Tipo de matriz: <class 'numpy.ndarray'>
Tipo de un elemento de matriz: <class 'numpy.ndarray'>


In [ ]:
f1 = np.array([1, 2, 3])
f2 = np.array([4, 5, 6])
f3 = np.array([7, 8, 9])
mm = np.array([f1, f2, f3])
print('Tipo de mm:',type(mm[0]))
print('mm:',mm)
print('matrix:',matriz)
print('\nSorpresa:\n', matriz == mm)

Tipo de mm: <class 'numpy.ndarray'>
mm: [[1 2 3]
 [4 5 6]
 [7 8 9]]
matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sorpresa:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Como se puede observar en  la última línea de la celda de código anterior,  el  operador `==` no compara la igualdad de dos arreglos de Numpy, sino que crea un arreglo donde en cada coordenada da el valor de la igualdad en la misma coordenada de los arreglos correspondiente.

Para comprobar que dos arrays NumPy son iguales existe una instrucción especial:

In [ ]:
if np.array_equal(matriz, mm):
    print("Los arrays son iguales")
else:
    print("Los arrays son diferentes")

Los arrays son iguales


**Tipos en un arreglo NumPy**

A diferencia de listas, los elementos de un arreglo de NumPy son todos del mismo tipo,  no podemos hacer arreglos heterogeneos. Los tipos de los elementos de un arreglo NumPy  son tipos propios de NumPy:

In [ ]:
arr_str = np.array(['este', 'es', 'un', 'vector'])
print(type(arr_str))
print(type(arr_str[0]))

<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [ ]:
arr_int = np.array([1, 2, 3, 4])
print(type(arr_int))
print(type(arr_int[0]))

<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
arr_str2 = np.array([1, '2', 3.0, 4])
print(type(arr_str2))
print(type(arr_str2[0]))

<class 'numpy.ndarray'>
<class 'numpy.str_'>


Observar que si cuando definimos un arreglo donde hay cadenas,  el arreglo se considera de cadenas.

In [ ]:
arr_float = np.array([1, 2., 3, 4])
print(type(arr_float))
print(type(arr_float[0]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


Observar que si cuando definimos un arreglo donde hay decimales y enteros,  el arreglo se considera de decimales.


**Inserción de elementos en un arreglo**

Para añadir elementos, NumPy tiene las funciones `insert()` y `append()`, que funcionan de manera similar a sus equivalentes en listas, pero en este caso son funciones y no métodos que se aplican a un array:


In [ ]:
z = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2, 7.])
# Añadimos el elemento 100 al array z, al final
print(z)
z = np.append(z, 100)
print(z)

[5.6 7.3 7.7 2.3 4.2 9.2 7. ]
[  5.6   7.3   7.7   2.3   4.2   9.2   7.  100. ]


In [ ]:
# Añadimos el elemento 200 al array z, en el tercer puesto (índice 2)
z = np.insert(z, 2, 200)
print(z)

[  5.6   7.3 200.    7.7   2.3   4.2   9.2   7.  100. ]



Como se ve, a diferencia de las listas, el primer parámetro es el array y luego el elemento que se quiere añadir, en el caso de `append()` y el array, la posición y luego elemento a añadir en el caso de `insert()`.

Si a un arrgelo Numpy  se la hace el append de una lista u otro arreglo Numpy  añade todos los elementos de la lista o arreglo  



In [ ]:
z = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2, 7.])
w = [1,2,3]
z = np.append(z, w)
print(z)

[5.6 7.3 7.7 2.3 4.2 9.2 7.  1.  2.  3. ]


Si se hace un `insert()` de una lista,  se inserta la lista o arreglo en la posición indicada.

In [ ]:
z = np.array([5.6, 7.3, 7.7, 2.3, 4.2, 9.2, 7.])
print(z)
u = np.array([1,2,3])
z = np.insert(z, 2, w)
print(z)

[5.6 7.3 7.7 2.3 4.2 9.2 7. ]
[5.6 7.3 1.  2.  3.  7.7 2.3 4.2 9.2 7. ]


La inserción de un `float` en un arreglo de `int` crea un arreglo de `float`. La inserción de un `int` en un arreglo de `float` transforma el `int` en `float` y lo inserta.

## 4. Indexación y asignación en NumPy
En esta sección, exploraremos la indexación y la asignación en arreglos NumPy.

Primero creamos un arreglo para ejemplificar las operaciones

In [ ]:
tupla_ejemplo = (0.2, 1.3, 2.4, 3.5, 4.6)
arr = np.array(tupla_ejemplo) # se puede convertir una tupla en array numpy
print(arr)

[0.2 1.3 2.4 3.5 4.6]


Este ejemplo es con un arreglo de 5 elementos de tipo `float`.

Podemos seleccionar (y retornar) un elemento específico desde un arreglo NumPy de la misma forma que realiza con una lista normal de Python: usando los corchetes.

Un ejemplo se ve a continuación:

In [ ]:
print(arr[0] , type(arr[0]))

0.2 <class 'numpy.float64'>


que imprime el valor de la primera posición del arreglo y su tipo.

Como podemos observar el tipo dentro de un arreglo NumPy es propio de NumPy.

También podemos referenciar múltiples elementos de un arreglo NumPy usando la notación slice. Por ejemplo,


In [ ]:
print(arr)
print(arr[0:2])
print(arr[2:4])
print(arr[:])
print(arr[0:4:2]) # es el arreglo desde el corte 0 al corte 4 saltando de a 2.

[0.2 1.3 2.4 3.5 4.6]
[0.2 1.3]
[2.4 3.5]
[0.2 1.3 2.4 3.5 4.6]
[0.2 2.4]


La última forma,  aunque no lo hemos visto,  se puede hacer en las litas usuales de Python:

In [ ]:
lista = [0.2, 1.3, 2.4, 3.5, 4.6]
lista[0:4:2]

[0.2, 2.4]

Observamos recién que la notación corchete y la notación slice de los arreglos de NumPy  se comporta de manera similar a la de listas de Python. Por otro lado,  veremos a continuación que la asignación se comporta en forma similar, pero no idéntica.

Podemos asignar nuevos valores a un elemento de un arreglo NumPy usando el operador `=`, al igual que las listas de Python normales. A continuación se muestran algunos ejemplos.



In [ ]:
print(arr)
arr[1] = 5.7
print(arr)

[0.2 1.3 2.4 3.5 4.6]
[0.2 5.7 2.4 3.5 4.6]


Pero NumPy ofrece algunas operaciones de asignación novedosas y que en muchos casos agilizan el trabajo.

Por  ejemplo,  si queremos que todos los valores del array tengan un valor determinado:

In [ ]:
arr[:] = 0.0
print(arr)

[0. 0. 0. 0. 0.]


reemplaza todos los valores de `arr` por `0.0`.

Definamos otro array:

In [ ]:
otro_arr = np.array([0.12, 0.94, 0.66, 0.73, 0.83])
print(otro_arr)

[0.12 0.94 0.66 0.73 0.83]


Podemos reemplazar los valores en cierto rango del array por un valor determinado:

In [ ]:
otro_arr[2:4] = 0.5
print(otro_arr)

[0.12 0.94 0.5  0.5  0.83]


Observar que reemplazó los índices 2 y 3 por el valor `0.5`.

Podemos también reemplazar una porción de un array por otro array del mismo tamaño que la porción:

In [ ]:
otro_arr[2:4] = np.array([6.5, 7.1])
print(otro_arr)

[0.12 0.94 6.5  7.1  0.83]


Hay muchas otras formas posibles de asignación  que resultan útiles para diversos contextos.

Hasta ahora en la sección, solo hemos explorado cómo hacer referencia a arreglos NumPy unidimensionales. Ahora exploraremos la indexación de matrices bidimensionales.


Para comenzar, creemos un arreglo NumPy de dos dimensiones llamado `mat`:


In [ ]:
mat = np.array([[5, 10, 15, 17],[20, 25, 30, 32],[35, 40, 45, 47]])
print(mat)

[[ 5 10 15 17]
 [20 25 30 32]
 [35 40 45 47]]


Hay dos formas de indexar un arreglo NumPy de dos dimensiones:

```
mat[fila, columna]
mat[fila][columna]
```

Por ejemplo, primero obtengamos la primera fila:


In [ ]:
mat[0, :]

array([ 5, 10, 15, 17])

Luego, obtengamos el último elemento de la primera fila:



In [ ]:
mat[0,-1]

17


También puede generar submatrices a partir de un arreglo NumPy bidimensional utilizando esta notación:

In [ ]:
mat[1:3,:]

array([[20, 25, 30, 32],
       [35, 40, 45, 47]])

In [ ]:
mat[1:3,1:2]

array([[25],
       [40]])

In [ ]:
mat[:,1]

array([10, 25, 40])

Cuando usamos `mat[:, 1]`, estamos seleccionando la segunda columna del arreglo `mat`. Esta operación devuelve un arreglo unidimensional (o vector) que contiene los elementos de la segunda columna.

In [ ]:
mat[:,1:2] #

array([[10],
       [25],
       [40]])

Cuando hacemos `mat[:, 1:2]`, estás seleccionando un "rebanada" del arreglo `mat` que incluye todas las filas y la segunda columna. Aunque estás seleccionando la misma columna que en el caso anterior, la diferencia es que la notación `1:`2 devuelve un subarreglo bidimensional,  en este caso 3 filas y 1 columna.

## 5. Referenciación de arreglos en NumPy

NumPy hace uso de un concepto llamado *referencia de arreglos* (array referencing) que es una fuente común de confusiones para las personas que son nuevas en la biblioteca.

Para entender la referencia de arreglos, primero veamos un ejemplo:


In [ ]:
new_array = np.array([6, 7, 8, 9])
print('new_array:', new_array)
second_new_array = new_array[1:3]
print('second_new_array:', second_new_array) # imprime [7 8]

new_array: [6 7 8 9]
second_new_array: [7 8]


In [ ]:
second_new_array[1] = 4
print(second_new_array) # imprime [7, 4], como se esperaba

[7 4]


In [ ]:
print('new_array:', new_array)

new_array: [6 7 4 9]


Observar que aunque no hemos reasignado directamente ningún elemento de `new_array`,  el tercer elemento pasó de valer `8` a valer `4`.

¿Que ha pasado? Lo  que pasó es que la modificación de `second_new_array` cambió también el valor de `new_array`.

¿Por qué es esto? Por defecto, NumPy *no* crea una copia de un arreglo cuando hace referencia a la variable del arreglo original usando el operador de asignación `=`. En cambio, simplemente apunta la nueva variable a la anterior, lo que permite que la segunda variable realice modificaciones en la variable original, incluso si esta no es nuestra intención.

Esto puede parecer extraño, pero tiene una explicación lógica. El propósito de la referencia de arreglos es conservar poder computacional. Al trabajar con grandes conjuntos de datos, rápidamente te quedarías sin RAM si crearas un nuevo arreglo cada vez que quisieras trabajar con una porción de él.


En  el caso que querramos una copia del arreglo existe una solución, se puede utilizar el método `copy` para copiar explícitamente un arreglo NumPy.

A continuación se muestra un ejemplo de esto.


In [ ]:
array_to_copy = np.array([1, 2, 3])
copied_array = array_to_copy[1:3].copy()
print(array_to_copy)
print(copied_array)

[1 2 3]
[2 3]


Como se puede ver a continuación, realizar modificaciones al arreglo copiado no altera el original.


In [ ]:
copied_array[0] = 9
print(copied_array)
print(array_to_copy)

[9 3]
[1 2 3]


La referencia de arreglos también se aplica a arreglos bidimensionales en NumPy, así que hay que asegurarse de utilizar el método `copy()` si se desea evitar modificar inadvertidamente un arreglo original después de guardar una porción de él en un nuevo nombre de variable.

## 6. Operaciones aritméticas con arreglos de NumPy

NumPy nos permite realizar operaciones aritméticas con arreglos. Puedes realizarlas usando el arreglo y un sólo número, o puedes realizarlas entre dos arreglos NumPy.

Exploramos cada una de las principales operaciones matemáticas a continuación.

Utilicemos algunos arreglos para hacer nuestro ejemplos.

In [ ]:
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([5, 8, 9, 10, 11])
arr_c = np.array([15, 28, 19, 10, 21, 5])

**Suma.**
Al sumar un sólo número a un arreglo de NumPy, ese número se suma a cada elemento en el arreglo. A continuación se ve un ejemplo:

In [ ]:
print(2 + arr_a)
print(arr_a)

[3 4 5 6 7]
[1 2 3 4 5]


Podemos sumar dos arreglos NumPy usando el operador `+`. Los arreglos se suman elemento por elemento (lo que significa que los primeros elementos se suman entre si, los segundos elementos se suman se suman entre si, y así sucesivamente).

A continuación se ve un ejemplo.

In [ ]:
arr_a = np.array([1, 2, 3, 4, 5])
arr_b = np.array([5, 8, 9, 10, 11])
arr_c = np.array([15, 28, 19, 10, 21, 5])
print(arr_a)
print(arr_b)
arr_d = arr_a + arr_b
print(arr_d)

[1 2 3 4 5]
[ 5  8  9 10 11]
[ 6 10 12 14 16]


In [ ]:
arr_d[0] = -1
print(arr_d)
print(arr_a)
print(arr_b)

[-1 10 12 14 16]
[1 2 3 4 5]
[ 5  8  9 10 11]


La suma de arreglos es asociativa y conmutativa.

Si intentamos sumar arreglos de distinto tamaño obtendremos una excepción. Por ejemplo


```
arr_a + arr_c
```

nos devuelve error.

**Elemento neutro de la suma y opuesto aditivo**

El elemento neutro de la suma es el arreglo cuyos valores son todos cero.

In [ ]:
arr_a + np.array([0, 0, 0, 0, 0])

array([1, 2, 3, 4, 5])

In [ ]:
arr_a + 0

array([1, 2, 3, 4, 5])

El opuesto aditivo de un arreglo se obtiene, como es lógico,  agregando el signo `-` al arreglo:

In [ ]:
-arr_a

array([-1, -2, -3, -4, -5])

In [ ]:
arr_a + (-arr_a)

array([0, 0, 0, 0, 0])

**Resta**

Como en los enteros o los número reales la resta se obtiene sumando el opuesto aditivo

In [ ]:
arr_a + (-arr_b)

array([-4, -6, -6, -6, -6])

Obviamente, se puede simplificar la notación:

In [ ]:
arr_a - arr_b

array([-4, -6, -6, -6, -6])

Operaciones con números tambiés se pueden hacer

In [ ]:
arr_a - 2

array([-1,  0,  1,  2,  3])

In [ ]:
2 - arr_a

array([ 1,  0, -1, -2, -3])

In [ ]:
(arr_a - 2) + (2 - arr_a)

array([0, 0, 0, 0, 0])

**Multiplicación**

La multiplicación también se realiza elemento por elemento tanto para casos de un sólo número como para casos de operaciones entre arreglos de NumPy.

A continuación se ven dos ejemplos.

In [ ]:
6 * arr_a

array([ 6, 12, 18, 24, 30])

In [ ]:
arr_a * arr_b

array([ 5, 16, 27, 40, 55])

*Observación.* Es posible multiplicar matrices con el operador `*` y la multiplicación se hace coordenada  a coordenada, es decir *NO* es la multiplicación de matrices del álgebra lineal.

Por supuesto la multiplicación de matrices, no coordenada a coordenada sino haciendo filas por columnas,  que verán más adelante en la materia de álgebra lineal,  también está implementada en NumPy.

In [ ]:
mat_A = np.array([[1, 0, 2, 3],[-1, 3, 2, 3],[3, 4, 4, 4]]) # matriz 3x4
mat_B = np.array([[2,3], [-1, 0], [2, 2], [-5,1]]) # matriz 4x2
np.dot(mat_A, mat_B) # multiplicar 3x4.4x2 resulta 3x2

array([[ -9,  10],
       [-16,   4],
       [-10,  21]])

**División**

En este punto, probablemente no te sorprende saber que la división en arreglos NumPy se realiza elemento por elemento. Un ejemplo:

In [ ]:
print(arr_a)
print(arr_a / 2)

[1 2 3 4 5]
[0.5 1.  1.5 2.  2.5]


También funciona bien la división entera:

In [ ]:
arr_a // 2

array([0, 1, 1, 2, 2])

La división entre arreglos de la misma longitud también es posible:

In [ ]:
print(arr_a)
print(arr_b)
print(arr_b / arr_a)
print(arr_b // arr_a)

[1 2 3 4 5]
[ 5  8  9 10 11]
[5.  4.  3.  2.5 2.2]
[5 4 3 2 2]


La división tiene una excepción notable en comparación con las otras operaciones matemáticas que hemos visto en esta sección. Dado que no podemos dividir por cero, al hacerlo, el campo correspondiente se completará con un valor `nan`, que es la abreviatura de Python para "No es un número" (“Not A Number”). Jupyter Notebook y Colab también imprimen una advertencia.

En el caso de Colab  el valor que toma la coordenada al ser dividida por 0 es `inf`


In [ ]:
arr_d = arr_a - 2
arr_d

array([-1,  0,  1,  2,  3])

In [ ]:
arr_e = arr_b / arr_d

<ipython-input-57-545c1364d91b>:1: RuntimeWarning: divide by zero encountered in divide
  arr_e = arr_b / arr_d


In [ ]:
arr_e

array([-5.        ,         inf,  9.        ,  5.        ,  3.66666667])

In [ ]:
type(arr_e[1])

numpy.float64

Observamos que NumPy considera `inf` un número más, pero,  sin embargo,  este número  no cumple  con los axiomas de los números reales: es más grande que cualquier número y otras particularidades del infinito.

In [ ]:
arr_e[1] > 10**2345566

True

El valor `inf` tiene otras propiedades que ustedes podrán explorar.

In [ ]:
-arr_e[1] > 10**2345566

False

In [ ]:
-arr_e[1] < -10**2345566

True

**Las funciones de NumPy actuan como un 'map' en un arreglo de NumPy**

Dada una función sobre algún tipo permitido en un arreglo, un *map* (es un concepto) consiste en iterar sobre un array y modificar sus elementos utilizando la función. La función entonces se ejecutará en cada uno de los elementos del array. Conceptualmente si $f$ es una función y, por ejemplo $[x_1, x_2, x_3, \ldots]$ es una arreglo  con $x_i$ en el dominio de $f$, entonces el *map de $f$*  en el arreglo es:
$$
\operatorname{map}(f)([x_1, x_2, x_3, \ldots]) = [f(x_1), f(x_2), f(x_3), \ldots]
$$

El módulo `numpy` tiene funciones similares al módulo `math`, pero que actúan sobre cada componente del arreglo,  es decir actúan como maps.

Usaremos este concepto en gran medida cuando grafiquemos funciones, pero veamos un ejemplo ahora.


In [ ]:
x = np.arange(0, 2*np.pi + 0.1, np.pi / 8)
 # crea un arreglo de 0 a un float menor que 2*np.pi + 0.1 incrementando
 # np.pi / 8
 # en cada paso
print(x)

[0.         0.39269908 0.78539816 1.17809725 1.57079633 1.96349541
 2.35619449 2.74889357 3.14159265 3.53429174 3.92699082 4.3196899
 4.71238898 5.10508806 5.49778714 5.89048623 6.28318531]


In [ ]:
print(np.sin(x))

[ 0.00000000e+00  3.82683432e-01  7.07106781e-01  9.23879533e-01
  1.00000000e+00  9.23879533e-01  7.07106781e-01  3.82683432e-01
  1.22464680e-16 -3.82683432e-01 -7.07106781e-01 -9.23879533e-01
 -1.00000000e+00 -9.23879533e-01 -7.07106781e-01 -3.82683432e-01
 -2.44929360e-16]


Dada una función que se aplica sobre números, podemos convertirla en un map  de un array NumPy con el método `vectorize()`, es decir si `f` es una función de números en números

    v_f = np.vectorize(f)

es una función que se aplica como map de `f` a arreglos numéricos. Por ejemplo,

In [ ]:
def f(x):
    return x**2

In [ ]:
v_f = np.vectorize(f)

x = np.array([1, 2, 3, 4, 5])
print(x)
print(v_f(x))

[1 2 3 4 5]
[ 1  4  9 16 25]


que hubiera sido lo mismo que

In [ ]:
print (x**2)

[ 1  4  9 16 25]


Pero para funciones más complejas conviene utilizar `vectorize()`.

La documentación de NumPy aclara que vectorizar una función no aumenta la eficiencia respecto a iterar sobre el arreglo y  aplicar la función en cada elemento. El método `vectorize()` se utiliza para escribir código más compacto.  

El código con iteraciones sería así:

In [ ]:
x = np.array([1, 2, 3, 4, 5])
print(x)
for i in range(len(x)):
    x[i] = x[i]**2
print(x)

[1 2 3 4 5]
[ 1  4  9 16 25]


Veremos luego  diferentes formas de iterar en arreglos NumPy, pero el ejemplo anterior nos muestra que las formas válidas para listas o cadenas también se pueden utilizar.

## 7. Métodos incorporados
Los arreglos de NumPy vienen con un número de métodos incorporados útiles. Analizaremos a continuación algunos de estos métodos con ejemplos.

**Obtener un rango de números utilizando Numpy**

NumPy tiene un método útil llamado `arange` que toma dos números y devuelve un arreglo de números enteros que son mayores o iguales al primer número y menores que el segundo número. Es muy parecido al método de Python `range`, pero `arange` devuelve un objeto `array` de NumPy

Un ejemplo del método `arange` es el siguiente.

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1.5, 5.5)

array([1.5, 2.5, 3.5, 4.5])

También se puede incluir una tercera variable en el método `arange` que proporciona un tamaño de paso. Pasar $2$ como tercera variable devolverá cada segundo número en el rango, pasar $5$ como tercera variable devolverá cada quinto número en el rango, y así sucesivamente. También podemos poner como tercer parámetro cualquier número (entero,  punto flotante)

Ejemplos de ejemplo de uso de la tercera variable en el método arange se encuentra a continuación.

In [ ]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,11,np.pi)

array([ 1.        ,  4.14159265,  7.28318531, 10.42477796])

**Generar arreglos de unos y ceros**

Mientras programas, de vez en cuando necesitará crear arreglos de unos o ceros. NumPy tiene métodos incorporados que te permiten hacer ambas cosas.

Podemos crear arreglos de ceros utilizando el método `zeros` de NumPy. Le pasas el número de enteros que quisieras crear como el argumento de la función. Un ejemplo es el siguiente.

In [ ]:
np.zeros(4)

array([0., 0., 0., 0.])

También se puedes hacer algo similar utilizando matrices. Por ejemplo,

In [ ]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a1 = np.array([1,20,30])
print(a1[1:2])
b1 = np.zeros(a1[1:2])
print(b1)

[20]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


 crea un arreglo de $5 \times 3$ que contiene todos ceros. Observar que debemos usar el doble paréntesis. Si queremos que los ceros sean de tipo entero, podemos hacer lo siguiente:

In [ ]:
np.zeros((5, 3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Podemos crear arreglos de unos usando un método similar llamado `ones`. Un ejemplo es el que sigue.


In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

o, un arreglo de unos enteros:

In [ ]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

**Dividir uniformemente un rango de números**

Hay muchas situaciones en las que se desea dividir un intervalo en intervalos regulares y  crear un arreglo con estos valores, algo así como *separe el intervalo de 1 a 10 en 10 subintervalos de igual longitud*. El método `linspace` de NumPy está diseñado para resolver este problema. `linspace` tiene tres argumentos:

1. El inicio del intervalo
2. El fin del intervalo
3. El número de subintervalos más 1 en los que deseas que se divida el intervalo

Un ejemplo del método `linspace` es el siguiente:

In [ ]:
print(np.linspace(0, 1, 11))
print(len(np.linspace(0, 1, 11)))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
11


Lo que devuelve es el arreglo con  los puntos de separación de los intervalos.

Haciendo una cuenta, podemos obtener  algo equivalente con `arange()`. Por ejemplo, en este caso los intervalos serán de $1/10 =0.1$ de ancho, luego:

In [ ]:
np.arange(0, 1 + 0.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

Obviamente,  hay que utilizar `linspace()` para cometer menos errores y por ser más fácil.

**Crear la matriz identidad**

En álgebra lineal hay concepto muy importante y es el de *matriz identidad*, que es un arreglo cuadrado cuyos valores diagonales son todos 1 y  las otras posiciones valen 0. NumPy tiene una función incorporada para construir matrices identidad. La función es `eye`.

Algunos ejemplos:

In [ ]:
np.eye(1)

array([[1.]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(50, dtype = int)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]])


**Números aleatorios usando NumPy**

NumPy tiene varios métodos integrados que te permiten crear matrices de números aleatorios. Cada uno de estos métodos comienza con `random`. A continuación se muestran algunos ejemplos:

In [ ]:
np.random.rand(10)

array([0.2983777 , 0.69507606, 0.37410726, 0.2300458 , 0.24297557,
       0.42915462, 0.38052813, 0.5067167 , 0.63572637, 0.71072974])

Devuelve un arreglo de 10 números aleatorios entre 0 y 1.

El tamaño de la muestra puede ser un número entero (para un arreglo unidimensional) o dos enteros separados por comas (para un arreglo bidimensional).

In [ ]:
np.random.rand(4, 3)*10

array([[6.60169349, 6.6229515 , 9.28809826],
       [2.93223868, 6.44561933, 8.31205509],
       [3.51285786, 0.29550514, 5.96597583],
       [2.96349962, 2.38928151, 9.17972454]])

Lo anterior devuelve una matriz $4 \times 3$ de números aleatorios entre 0 y 10.

Se pueden obtener números aleatorios entre 0 y 1, siguiendo la distribución normal:


In [ ]:
np.random.randn(30)

array([ 0.57898079, -0.31468369,  0.5658963 , -0.07599016, -0.51979715,
       -0.76583369,  0.67031251, -0.75737784, -0.63555371,  0.08839179,
       -1.51891764,  0.497266  , -2.10787107,  0.43127675, -0.2915617 ,
       -0.31137412, -1.26449563, -0.17821829, -1.28286351, -0.62005092,
        1.15652031, -0.00724021,  1.46690131,  0.03243399, -0.63394414,
        0.35969558,  0.80380967,  1.46059777,  0.04614124,  0.41146677])


En  el caso de números aletorios enteros se usa `randint`.


In [ ]:
np.random.randint(-20, 20, 10)

array([ 19,  -5, -13,  -2,   4, -13,  13,   1,   6, -15])

Devuelve una muestra de 10 números enteros que son mayores o iguales que -20 y menores que 20.

**Remodelar arreglos de NumPy**

Es muy común tomar un arreglo con ciertas dimensiones y transformar ese arreglo en una forma diferente. Por ejemplo, es posible que tengas un arreglo unidimensional con 6 elementos y desees cambiarlo a un arreglo bidimensional de 2x3.

A continuación se muestra un ejemplo:

In [ ]:
arr = np.array([0,1,2,3,4,5])
print(arr)
arr.reshape(2,3)

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

La salida de esta operación es:


```
array([[0, 1, 2],
       [3, 4, 5]])
```

Hay que tener en cuenta que para usar el método `reshape`, el arreglo original debe tener la misma cantidad de elementos que la multiplicación de los argumentos del método `reshape`.

Si se duda sobre las dimensiones de un arreglo NumPy, se puede determinar sus dimensiones utilizando el atributo `shape` de NumPy. Por  ejemplo:

In [ ]:
arr = np.array([0,1,2,3,4,5])
print(arr.shape)
arr = arr.reshape(2,3)
print(arr.shape)
print(arr)
print(type(arr[0]))
arr_2 = np.array([[0, 1, 2],  [3, 4, 5]])
print(arr_2)
print(type(arr_2[0]), arr_2[0])

(6,)
(2, 3)
[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'>
[[0 1 2]
 [3 4 5]]
<class 'numpy.ndarray'> [0 1 2]


El método `shape` es el adecuado para averiguar el tamaño de los arreglos con los cuales estamos trabajando. Aplicar la función `len` solo devuelve en número de filas del arreglo.

In [ ]:
len(arr)

2

**Métodos de estadística sobre un arreglo NumPy**

Aprendamos cuatro métodos útiles para identificar los valores máximo y mínimo dentro de un arreglo NumPy. Trabajaremos con este arreglo:


In [ ]:
simple_array = [1, 2., 3, 8, 30, 5]
z = np.array(simple_array)
print(z)

[ 1.  2.  3.  8. 30.  5.]


Además de las operaciones aritméticas básicas, los arrays de NumPy tienen métodos o funciones específicas para estadística. Algunas de ellas son las siguientes:


In [ ]:
z.max()   # Valor máximo de los elementos del array

30.0

In [ ]:
z.argmax() # índice donde se encuentra el máximo

4

In [ ]:
z.min()   # Valor mínimo de los elementos del array

1.0

In [ ]:
z.mean()  # Valor medio de los elementos del array

8.166666666666666

In [ ]:
z.std()   # Desviación típica de los elementos del array

10.023583302503264

In [ ]:
z.sum()   # Suma de todos los elementos del array

49.0

In [ ]:
print(np.median(z)) # Mediana de los elementos del array
x =np.array([1, 2., 3, 8, 30, 5, 20])
np.median(x)

4.0


5.0


Los métodos, que se operan de la forma `z.sum()` también pueden usarse como funciones de tipo `sum(z)`, etc. Consulten el manual de NumPy para conocer otras propiedades y métodos de los arrays o simplemente acudan y consulten la “ayuda” de las funciones que quieran utilizar.

In [ ]:
sum(z)

49.0

## 8. Arrays booleanos

Una gran utilidad de los arrays es la posibilidad de usarlos con datos booleanos (`True` o `False`) y operar entre ellos o incluso mezclados con arrays con números. Veamos algunos ejemplos:

In [ ]:
A = np.array([True, False, True])
B = np.array([False, False, True])
print(type(A[0]))

<class 'numpy.bool_'>


Podemos hacer el "y" de array booleanos con  el `*`:

In [ ]:
print(A*B)

[False False  True]


En este ejemplo vemos cómo al multiplicar dos arrays booleanos es resultado es otro array booleano hacien el "y" coordenada a coordenada. Para hacer el "o" usamos el operador `+` y para hacer la negación el `~`:

In [ ]:
print(A+B)
print(~A)

[ True False  True]
[False  True False]


Pero al multiplicar los arrays booleanos con arrays numéricos, el resultado es un array numérico con los mismos elementos, pero con los elementos que fueron multiplicados por `False` iguales a cero.

In [ ]:
C = np.array([1, 2, 3])
print('A =',A)
print('C =',C)
print('A*C =',A*C)

A = [ True False  True]
C = [1 2 3]
A*C = [1 0 3]


En  realidad en este tipo de operaciones el array booleano puede ser visto como un array numérico con `0` en `False` y `1` en `True`, como podemos ver en este ejemplo:  

In [ ]:
print('B =',B)
print('C =',C)
print('B+C =',B+C)

B = [False False  True]
C = [1 2 3]
B+C = [1 2 4]


Tambíén es posible usar los arrays como índices de otro array y como índices se pueden usar arrays numéricos o booleanos. El resultado será:

- si el array que se usa de índice es numérico (enteros no negativos), se devolverá el subarray con eso índices,
- si el array que se usa de índice es booleano (de `True` y `False`), debe tener la misma longitud del array original y devuelve  el subarray de las posiciones correspondientes a `True`

Hagamos algunos ejemplos.


In [ ]:
# Array con enteros de 0 a 90, de 10 en 10
mi_array = np.arange(0,100,10)
print(mi_array)

[ 0 10 20 30 40 50 60 70 80 90]


In [ ]:
# Array de índices numericos con numeros de 0-9 de 2 en 2
indices1 = np.arange(0,10,2)
print(indices1)

[0 2 4 6 8]


In [ ]:
# Array de 10 índices booleanos
indices2 = np.array([False, True, True, False, False, True, False, False, True, True])
print(indices2)

[False  True  True False False  True False False  True  True]


In [ ]:
print(mi_array)
print(mi_array[indices1]) # solo aprecen los valores con índice en indices1
print(mi_array[indices2]) # solo aparecen  los valores con índices True en indices2

[ 0 10 20 30 40 50 60 70 80 90]
[ 0 20 40 60 80]
[10 20 50 80 90]


Solo es admisible utilizar como índices arreglos de enteros o arreglos de booleanos y  estos últimos deben tener la misma longitud que el arreglo que se está indizando.

También es muy sencillo crear arrays booleanos usando operadores lógicos y luego usalos como índices, por ejemplo:

In [ ]:
# Creamos un array booleano usando un operador booleano
mayores50 = mi_array > 50
print(mayores50)

[False False False False False False  True  True  True  True]


Este array puede servir como índice para recuperar un subarray.

In [ ]:
print(mi_array[mayores50])

[60 70 80 90]


La creación de array booleanos para ser usados como índices de arrays numéricos es una característica *muy útil* y *muy utilizada* en NumPy (remarcamos esto). A estos array booleanos suele llamárselos *máscaras* y se utilizan, por ejemplo, para "limpiar" datos espurios de una muestra.

## 9. Iterar sobre arreglos Numpy

Iterar un arreglo NumPy se puede realizar de varias formas, dependiendo de tus necesidades específicas. Aquí hay algunas de las maneras más comunes:

### 9.1. Iterar sobre los elementos del arreglo (arreglo unidimensional)

Si tienes un arreglo unidimensional, puedes iterar sobre sus elementos de manera similar a cómo lo harías con una lista en Python.



In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

for element in arr:
    print(element)

1
2
3
4
5


### 9.2. Iterar sobre las filas de un arreglo bidimensional

Esto es escencialmente lo mismo que se hace en el punto anterior, pero ahora los elementos son filas.

In [ ]:
mat = np.array([[5, 10, 15, 17],
                [20, 25, 30, 32],
                [35, 40, 45, 47]])

for row in mat:
    print(row)

[ 5 10 15 17]
[20 25 30 32]
[35 40 45 47]


### 9.3. Iterar sobre los elementos de un arreglo bidimensional (anidando loops)

Puedes anidar loops para iterar sobre cada elemento en un arreglo bidimensional. Es exactamente igual a como se hace en listas de listas.


In [ ]:
for row in mat:
    for element in row:
        print(element)

5
10
15
17
20
25
30
32
35
40
45
47


### 9.4. Iterar usando `nditer`

NumPy proporciona `np.nditer` para iterar de manera eficiente sobre cualquier arreglo, independientemente de su forma.

In [ ]:
for element in np.nditer(mat):
    print(element)

5
10
15
17
20
25
30
32
35
40
45
47


### 9.5. Iterar con `enumerate`

Si necesitas los índices junto con los elementos, puedes usar `enumerate`.

#### Unidimensional


In [ ]:
for index, element in enumerate(arr):
    print(f"Index: {index}, Element: {element}")

Index: 0, Element: 1
Index: 1, Element: 2
Index: 2, Element: 3
Index: 3, Element: 4
Index: 4, Element: 5


#### Bidimensional

Para un arreglo bidimensional, puedes anidar `enumerate` para obtener tanto las filas como las columnas.


In [ ]:
for i, row in enumerate(mat):
    for j, element in enumerate(row):
        print(f"Row: {i}, Column: {j}, Element: {element}")

Row: 0, Column: 0, Element: 5
Row: 0, Column: 1, Element: 10
Row: 0, Column: 2, Element: 15
Row: 0, Column: 3, Element: 17
Row: 1, Column: 0, Element: 20
Row: 1, Column: 1, Element: 25
Row: 1, Column: 2, Element: 30
Row: 1, Column: 3, Element: 32
Row: 2, Column: 0, Element: 35
Row: 2, Column: 1, Element: 40
Row: 2, Column: 2, Element: 45
Row: 2, Column: 3, Element: 47


### 9.6. Iterar con `np.ndenumerate`

`np.ndenumerate` es útil para iterar sobre todos los elementos de un arreglo junto con sus índices.



In [ ]:
for index, element in np.ndenumerate(mat):
    print(f"Index: {index}, Element: {element}")

Index: (0, 0), Element: 5
Index: (0, 1), Element: 10
Index: (0, 2), Element: 15
Index: (0, 3), Element: 17
Index: (1, 0), Element: 20
Index: (1, 1), Element: 25
Index: (1, 2), Element: 30
Index: (1, 3), Element: 32
Index: (2, 0), Element: 35
Index: (2, 1), Element: 40
Index: (2, 2), Element: 45
Index: (2, 3), Element: 47


## Ejemplos

1. Crear un array de 120 números enteros aleatorios con valores de -100 a +100. Usando arrays de booleanos crear otros arrays que contengan los positivos, los negativos, los mayores de 50 y los $x$ tal que $-50 < x < 50$ del array original.

**Solución:**

In [ ]:
original = np.random.randint(-100, 100, 120)
print(original)

[-40  80  27 -57  17  10 -83  -3  35 -27 -55 -15  89 -22 -86 -74 -89  41
  60  71 -20  76  70  -5  91 -25  89 -73  60 -97  13  27 -13  55   6  12
   1  -1 -20  98  23  65 -87  64 -88  10 -51 -11  -9  57 -69  71  44  72
   9   9 -81  55   0  54  39  63  56  -7 -80 -26 -68  17  22 -47  77  43
 -32  12  97 -80  26  29 -23 -24  12  48 -32  26 -32  55  34  -8  69  71
  50  -2 -46   7 -37 -20 -40 -35 -17 -91 -30   4 -29  33 -36 -97  50  75
 -34  77  69  29 -72 -16  -7 -54  48  29  81  37]


In [ ]:
positivos = original > 0
orig_pos = original[positivos]
print(orig_pos)

[80 27 17 10 35 89 41 60 71 76 70 91 89 60 13 27 55  6 12  1 98 23 65 64
 10 57 71 44 72  9  9 55 54 39 63 56 17 22 77 43 12 97 26 29 12 48 26 55
 34 69 71 50  7  4 33 50 75 77 69 29 48 29 81 37]


In [ ]:
negativos = original < 0
orig_neg = original[negativos]
print(orig_neg)

[-40 -57 -83  -3 -27 -55 -15 -22 -86 -74 -89 -20  -5 -25 -73 -97 -13  -1
 -20 -87 -88 -51 -11  -9 -69 -81  -7 -80 -26 -68 -47 -32 -80 -23 -24 -32
 -32  -8  -2 -46 -37 -20 -40 -35 -17 -91 -30 -29 -36 -97 -34 -72 -16  -7
 -54]


In [ ]:
mayores50 = original > 50
orig_may50 = original[mayores50]
print(orig_may50)

[80 89 60 71 76 70 91 89 60 55 98 65 64 57 71 72 55 54 63 56 77 97 55 69
 71 75 77 69 81]


In [ ]:
intervalo1 = -50 < original # mayores que -50
intervalo2 = original < 50 # menores que 50
intervalo = intervalo1 * intervalo2 # los x tales que -50 < x < 50
orig_int = original[intervalo]
print(orig_int)

[-40  27  17  10  -3  35 -27 -15 -22  41 -20  -5 -25  13  27 -13   6  12
   1  -1 -20  23  10 -11  -9  44   9   9   0  39  -7 -26  17  22 -47  43
 -32  12  26  29 -23 -24  12  48 -32  26 -32  34  -8  -2 -46   7 -37 -20
 -40 -35 -17 -30   4 -29  33 -36 -34  29 -16  -7  48  29  37]


Así como el  `*` actúa como un  `and` entre booleanos,  el `+` actúa como un `or`. Veamos un ejemplo:

In [ ]:
intervalo = ( original < -50) + (original > 50) # los extremos,  es decir los x tal (x < -50) or (x > 50)
orig_extremos = original[intervalo]
print(orig_extremos)

[ 80 -57 -83 -55  89 -86 -74 -89  60  71  76  70  91  89 -73  60 -97  55
  98  65 -87  64 -88 -51  57 -69  71  72 -81  55  54  63  56 -80 -68  77
  97 -80  55  69  71 -91 -97  75  77  69 -72 -54  81]


2. La nota final de una materia de la Facultad, digamos $F$, se calcula añadiendo a la nota del examen final ($Z$) una ponderación de la evaluación contínua ($C$) a lo largo del curso de la forma:
$$
P = 0.6\,C + Z \frac{(10 - 0.6\,C)}{10}
$$
El alumno estará aprobado cuando $P$ sea mayor o igual a cinco, siempre que $Z$ supere un tercio de la nota máxima ($Z>10/3$). En  ese cas $F= P$. En caso contrario, se queda con $F=Z$. Un grupo de alumnos ha obtenido las siguientes calificaciones en la evaluación contínua y en el examen final:
$$
\begin{matrix}
&&	a_0& a_1& a_2& a_3& a_4& a_5& a_6& a_7& a_8& a_9 \\
C&&	8.2& 0.0& 9.0& 5.0& 8.4& 7.2& 5.0& 9.2& 4.9& 7.9 \\
Z&&	7.1& 5.1& 8.8& 3.1& 4.6& 2.0& 4.1& 7.4& 4.4& 8.8
\end{matrix}
$$

Usando arrays de NumPy hacer un programa que calcule sus notas finales indicando además quién ha aprobado y quién no. Calcular también la nota media de la evaluación continua, del examen final y de la nota final.

**Solución:** Primero creemos las estructuras necesarias para poder trabajar.

In [ ]:
import numpy as np
alumnos = np.array(['a_0', 'a_1', 'a_2', 'a_3', 'a_4', 'a_5', 'a_6', 'a_7', 'a_8', 'a_9'])
eval_c = np.array([8.2, 0.0, 9.0, 5.0, 8.4, 7.2, 5.0, 9.2, 4.9, 7.9])
eval_z = np.array([7.1, 5.8, 8.8, 3.1, 4.6, 2.0, 4.1, 7.4, 4.4, 8.8])
eval_p = 0.6 * eval_c + eval_z * (10 - 0.6 * eval_c) / 10
print(eval_c)
print(eval_z)
print(eval_p)

[8.2 0.  9.  5.  8.4 7.2 5.  9.2 4.9 7.9]
[7.1 5.8 8.8 3.1 4.6 2.  4.1 7.4 4.4 8.8]
[8.5268 5.8    9.448  5.17   7.3216 5.456  5.87   8.8352 6.0464 9.3688]


Antes de hacer las cuentas escribamos la lógica de la nota para un alumno. Si
$$
P =  0.6\,C + Z \displaystyle\frac{(10 - 0.6\,C)}{10},
$$
entonces
$$
F = \left\{
    \begin{matrix}
    P & &\text{si }&\quad Z > 1/3 \;\wedge\; P \ge 5 \\
    Z & &\text{}& \text{en caso contrario.}
    \end{matrix}
    \right.
$$
Entonces $F$  será la nota final.

Veamos los alumnos aprobados:

In [ ]:
criterio_1 = eval_z >= 10/3
criterio_2 = eval_p >= 5
criterio_aprobado = criterio_1 * criterio_2
aprobados = alumnos[criterio_aprobado]
print(aprobados)

['a_0' 'a_1' 'a_2' 'a_4' 'a_6' 'a_7' 'a_8' 'a_9']


Hacer el array con las notas finales es un poco más complicado. Recordemos que multiplicar por un array lógico es como multiplicar por 1s y 0s (`True` y `False`, respectivamente).

In [ ]:
print(eval_p * criterio_aprobado)
print(eval_z * ~criterio_aprobado)
eval_f = eval_p * criterio_aprobado + eval_z * ~criterio_aprobado
eval_f = np.round(eval_f)
print('Notas finales:', eval_f)

[8.5268 5.8    9.448  0.     7.3216 0.     5.87   8.8352 6.0464 9.3688]
[0.  0.  0.  3.1 0.  2.  0.  0.  0.  0. ]
Notas finales: [9. 6. 9. 3. 7. 2. 6. 9. 6. 9.]


Podemos,  además, como pide la consigna, calcular algunos datos estadísticos sobre el curso:

In [ ]:
print('Promedio de las evaluaciones continuas:', np.round(eval_c.mean(),1))
print('Promedio de las notas del examen final:', np.round(eval_z.mean(),1))
print('Promedio de las notas finales:', eval_f.mean())

Promedio de las evaluaciones continuas: 6.5
Promedio de las notas del examen final: 5.6
Promedio de las notas finales: 6.6


##10. Operadores booleanos

En NumPy, los operadores lógicos se utilizan para realizar operaciones booleanas elemento a elemento en arrays. Los principales operadores lógicos en NumPy son:

- `a & b`: Devuelve un array booleano con `True` donde ambos elementos `a` y `b` son `True`. Es equivalente al operador `and` en Python.

- `a | b`: Devuelve un array booleano con `True` donde al menos uno de los elementos en `a` o `b` es `True`. Es equivalente al operador `or` en Python.

- `~a`: Devuelve un array booleano con los elementos negados, es decir, `False` donde `a` es `True` y viceversa. Es equivalente al operador `not` en Python

Ejemplos:

In [ ]:
import numpy as np

a = np.array([True, False, True])
b = np.array([True, True, False])

print(a & b)  # [True False False]
print(a | b)   # [True True True]
print(~a)     # [False True False]

[ True False False]
[ True  True  True]
[False  True False]


Estos operadores lógicos en NumPy son muy útiles para filtrar y seleccionar elementos en arrays basados en condiciones booleanas.


**Ejemplo.** Crear un arreglo de 50  elementos con números enteros elegidos al azar entre 0 y 100.

1. Obtener el subarreglo de enteros positivos divisibles por 3.
2. Obtener el subarreglo  de los enteros que dividen a 120 o son mayores que 80.
3. Obtener el arrego complementario al anterior.

In [ ]:
arreglo = np.random.randint(0, 100, 50)
print(arreglo)

[98 32 45 27 43  8 87 92  7 57 96 27 50 95 79 95 93 41 58  6 90 94 46 22
 86 83 38 31 95 59 77 52 82 92 90 40 72 69  0 19 60 42 54 52 17 67 15 52
 73  3]


In [ ]:
# Solución de 1.
pos3 = arreglo[(arreglo >0) & (arreglo % 3 == 0)]
print(pos3)

[45 27 87 57 96 27 93  6 90 90 72 69 60 42 54 15  3]


Siempre debemos poner entre paréntesis las expresiones  que conecta el `&` o el `|`, pues sin los paréntesis la interpretación que hace NumPy de las expresiones puede ser ambigua o no corresponder a lo que nosotros queremos.

In [ ]:
# Solución de 2.
arreglo_2  = arreglo[(120 % arreglo == 0) | (arreglo > 80)]
print(arreglo_2)

[98  8 87 92 96 95 95 93  6 90 94 86 83 95 82 92 90 40  0 60 15  3]


<ipython-input-132-2593075f4e69>:2: RuntimeWarning: divide by zero encountered in remainder
  arreglo_2  = arreglo[(120 % arreglo == 0) | (arreglo > 80)]


Para 3., encontramos el complemento negando la expresión lógica de 2.:

In [ ]:
# Solución de 3.
arreglo_3 = arreglo[~((120 % arreglo == 0) | (arreglo > 80))]
print(arreglo_3)

[32 45 27 43  7 57 27 50 79 41 58 46 22 38 31 59 77 52 72 69 19 42 54 52
 17 67 52 73]


<ipython-input-133-5013561f1b01>:2: RuntimeWarning: divide by zero encountered in remainder
  arreglo_3 = arreglo[~((120 % arreglo == 0) | (arreglo > 80))]


Obviamente usando las leyes de  De Morgan, y  un poco más, podemos obtener una expresión sin negaciones de `~((120 % arreglo == 0) | (arreglo > 80))`:

 `~((120 % arreglo == 0) | (arreglo > 80))`  $\quad\equiv$

 `~(120 % arreglo == 0) & ~(arreglo > 80)`  $\quad\equiv$

 `(120 % arreglo != 0) & (arreglo <= 80)`.

 Es  decir, el complemto de los valores que dividen a 120 o son mayores que 80, son los valores que no dividen a 120 y  son menores o iguales a 80.

 En código:




In [ ]:
arreglo_3_v2 = arreglo[(120 % arreglo != 0) & (arreglo <= 80)]
print(arreglo_3_v2)

[32 45 27 43  7 57 27 50 79 41 58 46 22 38 31 59 77 52 72 69 19 42 54 52
 17 67 52 73]


<ipython-input-134-a606f7d64c9e>:1: RuntimeWarning: divide by zero encountered in remainder
  arreglo_3_v2 = arreglo[(120 % arreglo != 0) & (arreglo <= 80)]


Obviamnete, para encontrar el complemento es más fácil negar que hacer lo que hicimos al final.

## 11. Eficiencia

Un artículo sobre la eficiencia de las diferentes librerías y lenguajes de programación  para el tratamiento de datos:

https://datapythonista.me/blog/how-fast-can-we-process-a-csv-file

El repositorio de los archivos que utiliza el artículo es:

 https://github.com/datapythonista/bench_csv

Estudiaremos ahora un caso muy particular para analizar la eficiencia de Python, Numpy y Pandas.

Pandas es una biblioteca de Python diseñada específicamente para el manejo y análisis de estructuras de datos. Su objetivo es convertirse en la herramienta de análisis y manipulación de datos de código abierto más potente y flexible en cualquier lenguaje de programación.



**Un test de eficiencia.**

Creamos un archivo CSV de 1 millon de líneas con 8 campos por línea cada campo tiene un entero aleatorio entre  $-2 \cdot 10^{8}$ y $2 \cdot 10^{8}$. Cada fila es considerada una $8$-upla y nuestra tarea es contar el número de $8$-uplas a distancia del origen menor que $2 \cdot 10^{8}$, es decir debemos contar las $8$-uplas de enteros $(x_1,x_2,\ldots,x_8)$ tales que
$$
\sqrt{x_1^2+x_2^2 +\cdots+x_8^2} < 2 \cdot 10^{8}.
$$
Programáticamente es muy sencillo hacerlo en Python puro, pero lo que nos interesa ahora es comparar eficiencias de hacerlo con Python puro, Numpy y Pandas. Estas eficiencias son en Colab y pueden no ser representativas en otras arquitecturas.

Cargamos algunas librerías genéricas y dos parámentros

In [ ]:
from random import randint
import csv
import math
import time

limite, distancia = 2*10**8, 2*10**8

Cramos el archivo CSV:

In [ ]:
with open("archivo.csv", "w") as f:
    f.write('camp0,camp1,camp2,camp3,camp4,camp5,camp6,camp7\n')
    for i in range(10**6):
        f.write(str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+','+
                str(randint(-limite,limite))+'\n')

El archivo generado tiene varias decenas de Mb (75 MBytes o algo parecido).

Solución con Python puro:

In [ ]:
# Python puro cargando el archivo
t_0 = time.time()
with open("archivo.csv") as f:
    counter = 0
    reader = csv.reader(f)
    next(reader) # omite la primera linea
    for row in reader:
        result = math.sqrt(sum([float(value)**2 for value in row]))
        if result < distancia:
            counter += 1
print('ok:',counter)
t_1 = time.time()
print('Tiempo:', t_1-t_0)

Podemos partir la solución en dos pasos. Primero cargamos el archivo cvs a una arreglo de Python  y luego contamos las filas que cumplen con la condición.

In [ ]:
# Abrir archivo y cargarlo a lista
t_0 = time.time()
archivo = []
with open("archivo.csv") as f:
    reader = csv.reader(f)
    next(reader)
    for row in reader:
        archivo.append(row)
t_1 = time.time()
print('Tiempo:', t_1-t_0)

In [ ]:
# Python puro con archivo precargado
t_0 = time.time()
counter = 0
# archivo es una lista creada en la celda de código anterior
for row in archivo:
    result = math.sqrt(sum([int(value)**2 for value in row]))
    if result < distancia:
        counter += 1
print('ok:', counter)
t_1 = time.time()
print('Tiempo:', t_1-t_0)

Aparentemente, conviene hacerlo de un solo paso.

Veamos una solución con Numpy.

In [ ]:
import numpy as np

Primero en dos pasos.

In [ ]:
# Cargar archivo (una lista definida antes) como array numpy
t_0 = time.time()
archivo_np = np.array(archivo, dtype=np.float64)
t_1 = time.time()
print('Tiempo:', t_1-t_0)

In [ ]:
# Con numpy con array precargado
t_0 = time.time()
counter = np.sum(np.sqrt(np.sum(archivo_np ** 2, axis = 1)) < distancia)
print('ok:',counter)
t_1 = time.time()
print('Tiempo:', t_1-t_0)

Con Numpy en un solo paso,  es decir abrir el archivo csv  como arreglo Numpy y hacer la verificación:

In [ ]:
t_0 = time.time()
counter = np.sum(np.sqrt(np.sum(np.loadtxt('archivo.csv', delimiter=",", skiprows=1, dtype = np.float64) ** 2, axis = 1)) < distancia)
print('ok:',counter)
t_1 = time.time()
print('Tiempo:', t_1-t_0)

De lo que hemos visto,  claramente esto es  lo más conveniente.

Con Pandas:

In [ ]:
import pandas as pd

In [ ]:
t_0 = time.time()

values = pd.read_csv("archivo.csv", engine="python").pow(2).sum(axis=1).pow(.5)
print(values[values < distancia].count())

t_1 = time.time()
print('Tiempo:', t_1-t_0)

Esto parece ser mucho más lento que Python puro  y Numpy. Sin embargo la literatura dice que es más eficiente. Eso se debe a que en realidad Colab no es la herramienta adecuada para analizar los problemas de eficiencia en este caso.