## 8. NumPy y PyPlot


### 1° Parte. NumPy

**Ejercicio 0.** Los siguientes ejercicios son para practicar operaciones elementales de NumPy.


1. Crear un arreglo: Crea un arreglo unidimensional con los números del 1 al 10.
2. Crear una matriz: Crea una matriz de 3x3 llena de ceros.
3. Matriz identidad: Crea una matriz identidad de tamaño 4x4.
4. Suma de arreglos: Dado dos arreglos, realiza la suma elemento a elemento.
5. Multiplicación por un escalar: Multiplica un arreglo por un escalar (por ejemplo, 2).
6. Redimensionar un arreglo: Convierte un arreglo unidimensional de 12 elementos en una matriz de 3x4.
7. Acceso a elementos: Accede al tercer elemento de un arreglo unidimensional y al elemento en la posición (1, 2) de una matriz.
8. Filtrar elementos: Crea un arreglo y filtra todos los números que son mayores que 5.
9. Calcular la media: Calcula la media y la desviación estándar de un arreglo.
10. Transponer una matriz: Transpone una matriz de 2x3 a 3x2.
11. Concatenar arreglos: Une dos arreglos verticalmente y horizontalmente.
12. Submatrices: Extrae una submatriz de una matriz dada.
13. Buscar elementos: Encuentra los índices de los elementos que son pares en un arreglo.
14. Ordenar un arreglo: Crea un arreglo desordenado y ordénalo.
15. Crear arreglos aleatorios: Genera un arreglo de 10 números aleatorios entre -100 y +100.
16. Suma de matrices: Suma dos matrices del mismo tamaño.
17. Producto punto: Calcula el producto punto entre dos vectores.
18. Elementos únicos: Encuentra los elementos únicos en un arreglo dado.
19. Operaciones booleanas: Crea un arreglo binario y conviértelo a booleano.
20. Guardar y cargar arreglos: Guarda un arreglo en un archivo y luego cárgalo nuevamente.

In [24]:
# Solución
import numpy as np

# 1. Crear un arreglo: Crea un arreglo unidimensional con los números del 1 al 10.
print("1. Crear un arreglo: Crea un arreglo unidimensional con los números del 1 al 10.")
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]))
# o bien: print(np.arange(1, 11))

# 2. Crear una matriz: Crea una matriz de 3x3 llena de ceros.
print("\n2. Crear una matriz: Crea una matriz de 3x3 llena de ceros.")
print(np.zeros((3, 3)))

# 3. Matriz identidad: Crea una matriz identidad de tamaño 4x4.
print("\n3. Matriz identidad: Crea una matriz identidad de tamaño 4x4.")
print(np.eye(4))

# 4. Suma de arreglos: Dado dos arreglos, realiza la suma elemento a elemento.
print("\n4. Suma de arreglos: Dado dos arreglos, realiza la suma elemento a elemento.")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

# 5. Multiplicación por un escalar: Multiplica un arreglo por un escalar (por ejemplo, 2).
print("\n5. Multiplicación por un escalar: Multiplica un arreglo por un escalar (por ejemplo, 2).")
a = np.array([1, 2, 3])
print(a * 2)

# 6. Redimensionar un arreglo: Convierte un arreglo unidimensional de 12 elementos en una matriz de 3x4.
print("\n6. Redimensionar un arreglo: Convierte un arreglo unidimensional de 12 elementos en una matriz de 3x4.")   
a = np.arange(12)
print(a.reshape(3, 4))

# 7. Acceso a elementos: Accede al tercer elemento de un arreglo unidimensional y al elemento en la posición (1, 2) de una matriz.
print("\n7. Acceso a elementos: Accede al tercer elemento de un arreglo unidimensional y al elemento en la posición (1, 2) de una matriz.")
a = np.array([1, 2, 3, 4, 5])
print(a[2])
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a[1, 2])

# 8. Filtrar elementos: Crea un arreglo y filtra todos los números que son mayores que 5.
print("\n8. Filtrar elementos: Crea un arreglo y filtra todos los números que son mayores que 5.")
a = np.array([1, 6, 4, 7, 9, 3, 8])
print(a[a > 5])

# 9. Calcular la media: Calcula la media y la desviación estándar de un arreglo.
print("\n9. Calcular la media: Calcula la media y la desviación estándar de un arreglo.")
a = np.array([1, 2, 3, 4, 5])
print("Media:", np.mean(a))
print("Desviación estándar:", np.std(a))

# 10. Transponer una matriz: Transpone una matriz de 2x3 a 3x2.
print("\n10. Transponer una matriz: Transpone una matriz de 2x3 a 3x2.")
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.T)

# 11. Concatenar arreglos: Une dos arreglos verticalmente y horizontalmente.
print("\n11. Concatenar arreglos: Une dos arreglos verticalmente y horizontalmente.")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Vertical:", np.vstack((a, b)))
print("Horizontal:", np.hstack((a, b)))

# 12. Submatrices: Extrae una submatriz de una matriz dada.
print("\n12. Submatrices: Extrae una submatriz de una matriz dada.")
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[1:, 1:])
# o bien: print(a[1:3, 1:3])

# 13. Buscar elementos: Encuentra los índices de los elementos que son pares en un arreglo.
print("\n13. Buscar elementos: Encuentra los índices de los elementos que son pares en un arreglo.")
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(a % 2 == 0))

# 14. Ordenar un arreglo: Crea un arreglo desordenado y ordénalo.
print("\n14. Ordenar un arreglo: Crea un arreglo desordenado y ordénalo.")
a = np.array([4, 2, 1, 3, 5])
print(np.sort(a))

# 15. Crear arreglos aleatorios: Genera un arreglo de 10 números aleatorios entre -100 y +100.
print("\n15. Crear arreglos aleatorios: Genera un arreglo de 10 números aleatorios entre -100 y +100.")
print(np.random.randint(-100, 100, 10))

# 16. Suma de matrices: Suma dos matrices del mismo tamaño.
print("\n16. Suma de matrices: Suma dos matrices del mismo tamaño.")
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(a + b)

# 17. Producto punto: Calcula el producto punto entre dos vectores.
print("\n17. Producto punto: Calcula el producto punto entre dos vectores.")
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

# 18. Elementos únicos: Encuentra los elementos únicos en un arreglo dado.
print("\n18. Elementos únicos: Encuentra los elementos únicos en un arreglo dado.")
a = np.array([1, 2, 1, 3, 4, 2, 5])
print(np.unique(a))

# 19. Operaciones booleanas: Crea un arreglo binario y conviértelo a booleano.
print("\n19. Operaciones booleanas: Crea un arreglo binario y conviértelo a booleano.")
a = np.array([1, 0, 1, 0, 1])
print(a.astype(bool))

# 20. Guardar y cargar arreglos: Guarda un arreglo en un archivo y luego cárgalo nuevamente.
print("\n20. Guardar y cargar arreglos: Guarda un arreglo en un archivo y luego cárgalo nuevamente.")
a = np.array([1, 2, 3, 4, 5])
np.save("arreglo.npy", a)
b = np.load("arreglo.npy")
print(b)


1. Crear un arreglo: Crea un arreglo unidimensional con los números del 1 al 10.
[ 1  2  3  4  5  6  7  8  9 10]

2. Crear una matriz: Crea una matriz de 3x3 llena de ceros.
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3. Matriz identidad: Crea una matriz identidad de tamaño 4x4.
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

4. Suma de arreglos: Dado dos arreglos, realiza la suma elemento a elemento.
[5 7 9]

5. Multiplicación por un escalar: Multiplica un arreglo por un escalar (por ejemplo, 2).
[2 4 6]

6. Redimensionar un arreglo: Convierte un arreglo unidimensional de 12 elementos en una matriz de 3x4.
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

7. Acceso a elementos: Accede al tercer elemento de un arreglo unidimensional y al elemento en la posición (1, 2) de una matriz.
3
6

8. Filtrar elementos: Crea un arreglo y filtra todos los números que son mayores que 5.
[6 7 9 8]

9. Calcular la media: Calcula la media y la desviación estándar de un arreglo.
Media: 3.0
Desviac

**Ejercicio 1.**

Escribir un programa que imprima un arreglo numpy de 100 de números aleatorios del 0 al 100.

In [5]:
# Solución
import numpy as np

# Generar un arreglo de 100 números aleatorios entre 0 y 100
arreglo_aleatorio = np.random.randint(0, 101, size=(100))

# Imprimir el arreglo
print(arreglo_aleatorio)

[ 11  94  22  40  85  78  91  97  22  55   1  58  37  24  65  51  23  37
  65  30  18  73  12  47  49  45  79  51   9  70  55  58  50  73  28  45
  48  22  65  18  81  10  61  62  93  85   4  12  68  88  12  87  85   1
  17  15  55  40  20  67  43  35  17  85  14  21  70  98  97  32  31  27
  76  60  31  31  32  79  14 100  59   9  31  70  25  42  56  81  58  55
  32  19  72  11  27  74  43  10  78  96]


**Ejercicio 2.**

Escribir un programa que imprima un arreglo numpy de 100 de números aleatorios del 0 al 10. Además, que imprima los índices de los elementos iguales a cero del arreglo.

*Ayuda:* la función `where()` de NumPy se puede utilizar  para encontrar la solución del ejercicio. La sintaxis es:

```Python
indices = np.where("expresión lógica")
```
Donde "expresión lógica",  es una condición que debe cumplir el arreglo. Por ejemplo
```Python
indices = np.where(arreglo > 0)
```
devuelve los índices de `arreglo` donde está ubicados los números positivos.


In [14]:
# Solución
import numpy as np

# Generar un arreglo de 100 números aleatorios entre 0 y 100
arreglo_aleatorio = np.random.randint(0, 11, size=(100))

# Imprimir el arreglo
print("Arreglo de números aleatorios:")
print(arreglo_aleatorio)

# Encontrar los índices de los valores mayores a 50
indices_iguales_a_0 = np.where(arreglo_aleatorio == 0) 
# Imprimir los índices
print("\nÍndices de los valores iguales a 0:")
print(indices_iguales_a_0[0])

Arreglo de números aleatorios:
[ 3  5 10  9  8  7  4  7  9  3  3  7  4  5  0  7  8  2 10  9  7  3  0 10
  0  6  8  2  3  2  8  9  4  2  8  4 10  4  7  1  6  3  1  9  1  0  2  1
  6 10  4  0  0 10  5  5 10  4  6  2 10 10  6 10 10  8  9  3  0  6  3  1
  5  3  3  7  2  9  6  0  3  1  0 10  0  6  6  8  8  4  2  8 10  5  0 10
  9  4  2  9]

Índices de los valores iguales a 0:
[14 22 24 45 51 52 68 79 82 84 94]


**Ejercicio 3.**

Escribir un programa que imprima un arreglo numpy de 100 de números aleatorios del 0 al 100. Además, que imprima los índices de los valores mayores a 50.

In [ ]:
# Solución
import numpy as np

# Generar un arreglo de 100 números aleatorios entre 0 y 100
arreglo_aleatorio = np.random.randint(0, 101, size=(100))

# Imprimir el arreglo
print("Arreglo de números aleatorios:")
print(arreglo_aleatorio)

# Encontrar los índices de los valores mayores a 50
indices_mayores_a_50 = np.where(arreglo_aleatorio > 50) 
# Imprimir los índices
print("\nÍndices de los valores mayores a 50:")
print(indices_mayores_a_50[0])

**Ejercicio 4.**

Crear las matrices:

\begin{equation}
\begin{bmatrix}
6 & 8 & 1\\
2 & 9 & 3\\
4 & 5 & 1
\end{bmatrix}
\quad \text{ y } \quad
\begin{bmatrix}
7 & 1 & -4\\
-2 & 0 & -6\\
-1 & 1 & -1
\end{bmatrix}
\end{equation}

y calcular el producto de las mismas componente a componente.

In [16]:
# Solución
import numpy as np

# Definir las matrices
matriz_a = np.array([[6, 8, 1],
                     [2, 9, 3],
                     [4, 5, 1]])

matriz_b = np.array([[7, 1, -4],
                     [-2, 0, -6],
                     [-1, 1, -1]])

# Calcular el producto componente a componente
producto_cc = matriz_a * matriz_b

# Imprimir las matrices y el resultado
print("Matriz A:")
print(matriz_a)

print("\nMatriz B:")
print(matriz_b)

print("\nProducto componente a componente:")
print(producto_cc)

Matriz A:
[[6 8 1]
 [2 9 3]
 [4 5 1]]

Matriz B:
[[ 7  1 -4]
 [-2  0 -6]
 [-1  1 -1]]

Producto componente a componente:
[[ 42   8  -4]
 [ -4   0 -18]
 [ -4   5  -1]]


**Ejercicio 5.**

Crear un array de 100 números enteros aleatorios con valores de -100 a +100. Usando arrays de booleanos crear otros arrays que contengan los índices de: los números positivos, los números negativos, los números pares y los números impares del array original.

In [17]:
# Solución
import numpy as np

# Crear un arreglo de 100 números enteros aleatorios entre -100 y +100
arreglo = np.random.randint(-100, 101, size=100)

# Imprimir el arreglo original
print("Arreglo original:")
print(arreglo)

# Crear arreglos booleanos para las condiciones
positivos = arreglo > 0
negativos = arreglo < 0
pares = (arreglo % 2 == 0)
impares = (arreglo % 2 != 0)

# Obtener los índices de los números que cumplen las condiciones
indices_positivos = np.where(positivos)[0]
indices_negativos = np.where(negativos)[0]
indices_pares = np.where(pares)[0]
indices_impares = np.where(impares)[0]

# Imprimir los resultados
print("\nÍndices de números positivos:")
print(indices_positivos)

print("\nÍndices de números negativos:")
print(indices_negativos)

print("\nÍndices de números pares:")
print(indices_pares)

print("\nÍndices de números impares:")
print(indices_impares)

Arreglo original:
[-91  67   7 -11  54  61  -4 -17 -63 -55  14  90  51  81   3 -44 -43 -36
 -26  20  -8  98 -24  11  99  47  59  57 -39 -47  14 -65 -96  19  34  77
  27 -54 -10  25 -34   8 -87  -5  89  80 -95  67 -80  96  82  21 -72  34
   4  30   4  84 -83 -38 -48   6  89 -11 -83  50  93 -65 -51   8 -86 -90
 -67  99  56 100  45 -91 -45   6 -28 -85 -76 -56  72  19 -94 -94  36  18
 -52   1 100 -28 -56 -59  64  49 -78  78]

Índices de números positivos:
[ 1  2  4  5 10 11 12 13 14 19 21 23 24 25 26 27 30 33 34 35 36 39 41 44
 45 47 49 50 51 53 54 55 56 57 61 62 65 66 69 73 74 75 76 79 84 85 88 89
 91 92 96 97 99]

Índices de números negativos:
[ 0  3  6  7  8  9 15 16 17 18 20 22 28 29 31 32 37 38 40 42 43 46 48 52
 58 59 60 63 64 67 68 70 71 72 77 78 80 81 82 83 86 87 90 93 94 95 98]

Índices de números pares:
[ 4  6 10 11 15 17 18 19 20 21 22 30 32 34 37 38 40 41 45 48 49 50 52 53
 54 55 56 57 59 60 61 65 69 70 71 74 75 79 80 82 83 84 86 87 88 89 90 92
 93 94 96 98 99]

Índices de núme

**Ejercicio 7**

Crea un array bidimensional 5x5 con todos los valores cero. Usando el indexado de arrays, asigna 1 a todos los elementos de la diagonal, para obtener la matiz identidad 5x5. Finalmente, asigna el valor 5 a todos los elementos de las subarrays 2x2 inferior izquierda y superior derecha de la matriz de 5x5.

In [23]:
# Solución
import numpy as np

# Crear un array 5x5 lleno de ceros
matriz = np.zeros((5, 5))
print("Matriz 5x5 de 0s:\n", matriz)

# Asignar 1 a todos los elementos de la diagonal
np.fill_diagonal(matriz, 1)
print("\nMatriz con 1s en la diagonal:\n", matriz)

# Asignar el valor 5 a la submatriz 2x2 inferior izquierda
matriz[3:5, 0:2] = 5
print("\nMatriz con 5s agregados en la submatriz 2x2 inferior izquierda:\n", matriz)

# Asignar el valor 5 a la submatriz 2x2 superior derecha
matriz[0:2, 3:5] = 5
print("\nMatriz con 5s agregados en la submatriz 2x2 superior derecha:\n", matriz)


Matriz 5x5 de 0s:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Matriz con 1s en la diagonal:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matriz con 5s agregados en la submatriz 2x2 inferior izquierda:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [5. 5. 0. 1. 0.]
 [5. 5. 0. 0. 1.]]

Matriz con 5s agregados en la submatriz 2x2 superior derecha:
 [[1. 0. 0. 5. 5.]
 [0. 1. 0. 5. 5.]
 [0. 0. 1. 0. 0.]
 [5. 5. 0. 1. 0.]
 [5. 5. 0. 0. 1.]]


**Ejercicio 8**

Los diámetros de las esporas del lycopodium pueden medirse por métodos interferométricos. Los resultados de uno de estos experimentos son los siguientes:
$$
\begin{matrix}
\text{k * diametro (cm)} & 14 & 15 & 16 & 17 & 18 & 19 & 20 & 21 & 22 & 23\\
\hline
\text{número de esporas} & 1 & 1 & 8 & 24 & 48 & 58 & 35 & 16 & 8 & 1 \\
\end{matrix}
$$
donde $k=5880$.
Usando funciones de numpy determinar, el diámetro medio de las esporas y la desviación estándar de la muestra. Separar, en arrays independientes, las medidas de los diámetros:

1. Que tengan valores inferiores a la media menos la desviación estándar, es decir $d < \overline{d} - \sigma_d$.
2. Que tengan valores superiores a la media más la desviación estándar, es decir $d > \overline{d} + \sigma_d$.
3. Que tengan valores entre $\overline{d} - \sigma_d < d < \overline{d} + \sigma_d$.

**Ejercicio 9**

Crear un array numpy de 150 números enteros aleatorios en el rango del 1 al 1000. Imrpimirla. Usando una máscara booleana, identificar los números divisibles entre 3 y mayores a 500. Imprimir los valores con su correspondiente ubicación en el arreglo original.

**Ejercicio 10**

1. Crear un array numpy de 80 números enteros aleatorios en el rango del 1 al 100. Imprimirla.

2. Escribe un programa que elige un número aleatorio del array del paso 1 y ordena el array. Primero se debe imprimir el array ordenado. Luego, el usuario tiene que adivinar el número y el programa le dice si su adivinanza es demasiado alta o demasiado baja. Si el usuario adivina el número en 6 o menos intentos, la función debe devolver `True`, de lo contrario, devuelve `False`.

*Ayuda:* `np.sort(arreglo)` ordena `arreglo`. `np.random.choice(arreglo)` elige un elemento al azar de `arreglo`.

### 2° Parte. PyPlot

**Ejercicio 11.1 - Gráfico de línea simple.** Crea un gráfico de línea que muestre la evolución de una serie de datos a lo largo del tiempo.


In [ ]:
datos = [1, 2, 3, 4, 5]

**Ejercicio 11.2 - Gráfico de dispersión.** Representa un conjunto de puntos en un plano cartesiano.

In [ ]:
x = [1, 2, 3, 4, 5]
y = [2, 3, 4, 5, 6]

**Ejercicio 11.3 - Histograma.** Muestra la distribución de frecuencia de un conjunto de datos.

In [ ]:
datos = [1, 1, 2, 3, 3, 3, 4, 4, 4, 4]

**Ejercicio 11.4 - Gráfico de barras.** Representa datos categóricos en forma de barras.

In [ ]:
categorias = ['A', 'B', 'C', 'D']
valores = [10, 20, 15, 25]

**Ejercicio 11.5 - Gráfico circular.** Muestra la proporción de diferentes categorías en un conjunto de datos.


In [ ]:
sizes = [20, 30, 25, 25]
labels = ['A', 'B', 'C', 'D']

**Ejercicio 12**

Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla un diagrama de líneas con la evolución de las ventas.

**Ejercicio 13**

Escribir una función que reciba una diccionario con las notas de las asignaturas de un curso y una cadena con el nombre de un color y devuelva un diagrama de barras de las notas en el color dado.

**Ejercicio 14**

Escribir una función que reciba un array de numpy con las notas de los alumnos de un curso y devuelva un diagrama de barras con las notas. El diagrama debe tener el título “Distribución de notas”.

**Ejercicio 15**

Escribir una función que reciba un array de numpy con el número de ventas de un producto durante los meses de un trimestre y un título y cree un gráfico circular con las ventas en formato png con el titulo dado. El diagrama debe guardarse en un fichero con formato png y el título dado.

**Ejercicio 16**

Escribir una función que reciba un arreglo numpy con el número de ventas de un producto por años y una cadena con el tipo de gráfico a generar (lineas, barras, sectores, areas) y devuelva un diagrama del tipo indicado con la evolución de las ventas por años y con el título “Evolución del número de ventas”.

**Ejercicio 17**

Escribir una función que reciba una matriz numpy con los ingresos y gastos de una empresa por meses y devuelva un diagrama de líneas con dos líneas, una para los ingresos y otra para los gastos. El diagrama debe tener una leyenda identificando la línea de los ingresos y la de los gastos, un título con el nombre “Evolución de ingresos y gastos” y el eje y debe empezar en 0.